server:
  port: 80
master:
  user:
    name: Gourav Chopra
    email: gouravchopra2019@gmail.com
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: myjrtpdisk
    password: Chprgourav@100
    properties:
      mail:
        smtp:
          starttls:
            enable: true