server:
  port: 80
  
master:
 user:
  name: Gourav Chopra
  email: gouravchopra2019@gmail.com
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health1.0
    username: root
    password: root
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: myjrtpdisk
    password: Chprgourav@100
    properties:
     mail:
      smtp:
       starttls:
         enable: true
             
